#!/usr/bin/env python3
"""Generate non-private Motion Photo test samples for LiveKit.

The generated files are synthetic fixtures. They contain no personal media.

Two Motion Photo variants are produced:

- ``motion_detect_only.MP.jpg`` uses a tiny MP4-like payload for detector and
  offset/size tests only.
- ``motion_playable.MP.jpg`` uses a real MP4 generated by ffmpeg when ffmpeg is
  available. It is intended for Google Photos / device-gallery playback checks.
"""

from __future__ import annotations

import argparse
import base64
import shutil
import struct
import subprocess
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT_DIR = REPO_ROOT / "testdata" / "synthetic" / "generated"


FALLBACK_JPEG_BASE64 = (
    "/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAP//////////////////////////////////////////////////////////////////////////////////////"
    "2wBDAf//////////////////////////////////////////////////////////////////////////////////////wAARCAABAAEDASIAAhEBAxEB/8QA"
    "FQABAQAAAAAAAAAAAAAAAAAAAAX/xAAUEAEAAAAAAAAAAAAAAAAAAAAA/9oADAMBAAIQAxAAAAH/xAAUEAEAAAAAAAAAAAAAAAAAAAAA/9oACAEBA"
    "AEFAqf/xAAUEQEAAAAAAAAAAAAAAAAAAAAA/9oACAEDAQE/AUf/xAAUEQEAAAAAAAAAAAAAAAAAAAAA/9oACAECAQE/AUf/xAAUEAEAAAAAAAAA"
    "AAAAAAAAAAAA/9oACAEBAAY/Aqf/xAAUEAEAAAAAAAAAAAAAAAAAAAAA/9oACAEBAAE/IV//2gAMAwEAAgADAAAAEP/EABQRAQAAAAAAAAAA"
    "AAAAAAAAABD/2gAIAQMBAT8QH//EABQRAQAAAAAAAAAAAAAAAAAAABD/2gAIAQIBAT8QH//EABQQAQAAAAAAAAAAAAAAAAAAABD/2gAIAQEA"
    "AT8QH//Z"
)


def box(kind: bytes, payload: bytes = b"") -> bytes:
    if len(kind) != 4:
        raise ValueError("MP4 box type must be exactly 4 bytes")
    return struct.pack(">I", len(payload) + 8) + kind + payload


def make_tiny_mp4_payload() -> bytes:
    """Return a small MP4-like payload suitable for offset/length tests."""
    ftyp = box(b"ftyp", b"isom" + struct.pack(">I", 0x200) + b"isomiso2mp41")
    free = box(b"free", b"LiveKit synthetic Motion Photo payload")
    mdat = box(b"mdat", b"\x00" * 32)
    return ftyp + free + mdat


def make_base_jpeg() -> bytes:
    """Create a tiny JPEG. Prefer Pillow if installed; otherwise use fallback bytes."""
    try:
        from PIL import Image  # type: ignore
        import io

        image = Image.new("RGB", (64, 64), (73, 156, 255))
        output = io.BytesIO()
        image.save(output, format="JPEG", quality=90)
        return output.getvalue()
    except Exception:
        return base64.b64decode(FALLBACK_JPEG_BASE64)


def make_xmp(video_length: int, *, presentation_timestamp_us: int = 0) -> bytes:
    xmp = f"""<?xpacket begin="" id="W5M0MpCehiHzreSzNTczkc9d"?>
<x:xmpmeta xmlns:x="adobe:ns:meta/">
  <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
    <rdf:Description
      xmlns:Camera="http://ns.google.com/photos/1.0/camera/"
      Camera:MotionPhoto="1"
      Camera:MotionPhotoVersion="1"
      Camera:MotionPhotoPresentationTimestampUs="{presentation_timestamp_us}"
      Camera:MicroVideo="1"
      Camera:MicroVideoVersion="1"
      Camera:MicroVideoOffset="{video_length}">
      <Container:Directory
        xmlns:Container="http://ns.google.com/photos/1.0/container/"
        xmlns:Item="http://ns.google.com/photos/1.0/container/item/">
        <rdf:Seq>
          <rdf:li rdf:parseType="Resource">
            <Item:Mime>image/jpeg</Item:Mime>
            <Item:Semantic>Primary</Item:Semantic>
            <Item:Padding>0</Item:Padding>
          </rdf:li>
          <rdf:li rdf:parseType="Resource">
            <Item:Mime>video/mp4</Item:Mime>
            <Item:Semantic>MotionPhoto</Item:Semantic>
            <Item:Length>{video_length}</Item:Length>
            <Item:Padding>0</Item:Padding>
          </rdf:li>
        </rdf:Seq>
      </Container:Directory>
    </rdf:Description>
  </rdf:RDF>
</x:xmpmeta>
<?xpacket end="w"?>"""
    return b"http://ns.adobe.com/xap/1.0/\x00" + xmp.encode("utf-8")


def insert_app1_xmp(jpeg: bytes, xmp_payload: bytes) -> bytes:
    if not jpeg.startswith(b"\xff\xd8"):
        raise ValueError("Base image is not a JPEG")
    segment_length = len(xmp_payload) + 2
    if segment_length > 0xFFFF:
        raise ValueError("XMP packet is too large for a single JPEG APP1 segment")
    app1 = b"\xff\xe1" + struct.pack(">H", segment_length) + xmp_payload
    return jpeg[:2] + app1 + jpeg[2:]


def make_motion_photo(jpeg: bytes, video_payload: bytes) -> bytes:
    return insert_app1_xmp(jpeg, make_xmp(len(video_payload))) + video_payload


def generate_playable_mp4(output_path: Path) -> bool:
    ffmpeg = shutil.which("ffmpeg")
    if ffmpeg is None:
        return False

    output_path.parent.mkdir(parents=True, exist_ok=True)
    command = [
        ffmpeg,
        "-y",
        "-f",
        "lavfi",
        "-i",
        "testsrc2=size=320x240:rate=30",
        "-t",
        "1.5",
        "-an",
        "-c:v",
        "libx264",
        "-profile:v",
        "baseline",
        "-level",
        "3.0",
        "-pix_fmt",
        "yuv420p",
        "-movflags",
        "+faststart",
        str(output_path),
    ]
    result = subprocess.run(command, capture_output=True, text=True)
    if result.returncode == 0 and output_path.exists() and output_path.stat().st_size > 0:
        return True

    fallback_command = [
        ffmpeg,
        "-y",
        "-f",
        "lavfi",
        "-i",
        "testsrc2=size=320x240:rate=30",
        "-t",
        "1.5",
        "-an",
        "-c:v",
        "mpeg4",
        "-pix_fmt",
        "yuv420p",
        "-movflags",
        "+faststart",
        str(output_path),
    ]
    result = subprocess.run(fallback_command, capture_output=True, text=True)
    return result.returncode == 0 and output_path.exists() and output_path.stat().st_size > 0


def write_samples(output_dir: Path) -> None:
    output_dir.mkdir(parents=True, exist_ok=True)

    base_jpeg = make_base_jpeg()
    mp4_payload = make_tiny_mp4_payload()
    motion_jpeg = make_motion_photo(base_jpeg, mp4_payload)

    (output_dir / "plain.jpg").write_bytes(base_jpeg)
    (output_dir / "motion_detect_only.MP.jpg").write_bytes(motion_jpeg)
    (output_dir / "broken_missing_xmp_appended_video.jpg").write_bytes(base_jpeg + mp4_payload)
    (output_dir / "broken_xmp_without_video.jpg").write_bytes(
        insert_app1_xmp(base_jpeg, make_xmp(len(mp4_payload)))
    )

    playable_mp4_path = output_dir / "motion_playable_source.mp4"
    has_playable_mp4 = generate_playable_mp4(playable_mp4_path)
    if has_playable_mp4:
        playable_mp4 = playable_mp4_path.read_bytes()
        (output_dir / "motion_playable.MP.jpg").write_bytes(
            make_motion_photo(base_jpeg, playable_mp4)
        )

    readme = """# Generated synthetic samples

These files are generated test fixtures and contain no personal data.

- `plain.jpg`: normal JPEG, should not be detected as Motion Photo.
- `motion_detect_only.MP.jpg`: JPEG with Motion Photo XMP and appended MP4-like payload.
- `motion_playable.MP.jpg`: JPEG with Motion Photo XMP and appended real MP4 payload, generated when ffmpeg is available.
- `motion_playable_source.mp4`: source MP4 used by `motion_playable.MP.jpg`, generated when ffmpeg is available.
- `broken_missing_xmp_appended_video.jpg`: appended payload but no Motion Photo XMP.
- `broken_xmp_without_video.jpg`: Motion Photo XMP but missing appended payload.

`motion_detect_only.MP.jpg` is for detector / stripper regression tests and is not intended to be a playable video.

`motion_playable.MP.jpg` should be validated on a real Android device with Google Photos or another gallery app. Local generation only proves the file structure and MP4 payload; it does not prove gallery compatibility.
"""
    (output_dir / "README.md").write_text(readme, encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT_DIR,
        help=f"Output directory. Default: {DEFAULT_OUTPUT_DIR}",
    )
    args = parser.parse_args()
    write_samples(args.output)
    print(f"Generated Motion Photo samples in: {args.output}")


if __name__ == "__main__":
    main()
